on:
  push:
    branches:
      - master
jobs:
  my_job:
    name: ${{ matrix.configm.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {name: "MINGW", os: "windows-latest"}
        - {name: "MSVC", os: "windows-latest"}
        - {name: "LINUX", os: "ubuntu-latest"}
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.4.0
      with:
        key: ${{ secrets.GITEE_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: GIT-CLONE
      run: |
        git config --global user.name "robot"
        git config --global user.email "libo_go@163.com"
        git clone git@gitee.com:shubci/libs.git
        mkdir module
        cd module
        git clone git@gitee.com:shubci/cjson.git cJSON
        git clone git@gitee.com:shubci/osal.git
        git clone git@gitee.com:shubci/trial_manager.git
        git clone git@gitee.com:shubci/device_manager.git
        git clone git@gitee.com:shubci/data_manager.git
        git clone git@gitee.com:shubci/Unity.git unittest
    - name: MINGW
      if: startsWith(matrix.config.name, 'MINGW')
      run: |
        cd cJSON
        git submodule update --init --recursive
        cmake -G "MinGW Makefiles" -S . -B ./build
        cd ./build
        make
        make install
        cd ../../osal
        git submodule update --init --recursive
        cmake -G "MinGW Makefiles" -S . -B ./build
        cd ./build
        make
        make install
        cd ../../unittest
        git submodule update --init --recursive
        cmake -G "MinGW Makefiles" -S . -B ./build
        cd ./build
        make
        make install
        cd ../../trial_manager
        git submodule update --init --recursive
        cmake -G "MinGW Makefiles" -S . -B ./build
        cd ./build
        make
        make install
        cd ../../device_manager
        git submodule update --init --recursive
        cmake -G "MinGW Makefiles" -S . -B ./build
        cd ./build
        make
        make install
        cd ../../data_manager
        git submodule update --init --recursive
        cmake -G "MinGW Makefiles" -S . -B ./build
        cd ./build
        make
        make install
        cd ../../../libs
        git status
        git add . && git commit -m "ci: auto build & publish"
        git push --force
        git log
      shell: pwsh
    - name: MSVC
      if: startsWith(matrix.config.name, 'MSVC')
      run: |
        cd cJSON
        git submodule update --init --recursive
        cmake -G "Visual Studio 17 2022" -S . -B ./build
        cmake --build ./build --target install
        cd ../../osal
        git submodule update --init --recursive
        cmake -G "Visual Studio 17 2022" -S . -B ./build
        cmake --build ./build --target install
        cd ../../unittest
        git submodule update --init --recursive
        cmake -G "Visual Studio 17 2022" -S . -B ./build
        cmake --build ./build --target install
        cd ../../trial_manager
        git submodule update --init --recursive
        cmake -G "Visual Studio 17 2022" -S . -B ./build
        cmake --build ./build --target install
        cd ../../device_manager
        git submodule update --init --recursive
        cmake -G "Visual Studio 17 2022" -S . -B ./build
        cmake --build ./build --target install
        cd ../../data_manager
        git submodule update --init --recursive
        cmake -G "Visual Studio 17 2022" -S . -B ./build
        cmake --build ./build --target install
        cd ../../../libs
        git status
        git add . && git commit -m "ci: auto build & publish"
        git push --force
        git log
      shell: pwsh
    - name: LINUX
      if: startsWith(matrix.config.name, 'LINUX')
      run: |
        cd cJSON
        git submodule update --init --recursive
        cmake -S . -B ./build && cd ./build && make && make install
        cd ../../osal
        git submodule update --init --recursive
        cmake -S . -B ./build && cd ./build && make && make install
        cd ../../unittest
        git submodule update --init --recursive
        cmake -S . -B ./build && cd ./build && make && make install
        cd ../../trial_manager
        git submodule update --init --recursive
        cmake -S . -B ./build && cd ./build && make && make install
        cd ../../device_manager
        git submodule update --init --recursive
        cmake -S . -B ./build && cd ./build && make && make install
        cd ../../data_manager
        git submodule update --init --recursive
        cmake -S . -B ./build && cd ./build && make && make install
        cd ../../../libs
        git status
        git add . && git commit -m "ci: auto build & publish"
        git push --force
        git log
